config/routes.rb
Ilictronix::Application.routes.draw do

  get 'signup' => 'users#new', :as => 'signup'
  get 'login'  => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'new' => 'posts#new', :as => 'new_post'

  post '/posts/:id/publicize' => 'posts#publicize', :as => 'publicize_post'

  resources :users
  resources :sessions
  resources :posts, :except => [:show, :update, :destroy]
  resources :comments
  resources :roles

  get '/tagged/:tag' => 'posts#tagged', :as => 'tag'
  get '/tagged/:tag/:page' => 'posts#tagged'

  get '/:id' => 'posts#show', :as => 'post'
  put '/:id' => 'posts#update'
  delete '/:id' => 'posts#destroy'

  post '/users/:id/attach' => 'users#attach', :as => 'attach'

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

  attr_accessible :body, :post_id

  validates_presence_of :body, :post_id, :user_id
  validates_length_of :body, :minimum => 10, :maximum => 1000

  def timestamp
    self.created_at.strftime("%b %e at %l:%M %p")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :require_login
  before_filter :admin_or_original?, :only => [:edit, :update, :destroy]

  def create
    @comment = Comment.new(params[:comment])
    @comment.user = current_user

    if @comment.save
      redirect_to @comment.post, :notice => 'Comment saved!'
    else
      redirect_to @comment.post, :alert => 'Comment too short (minimum 10 chars)'
    end
  end

  def edit
    # we get @comment in admin_or_original?
    render :edit, :layout => 'no_sidebar'
  end

  def update
    # we get @comment in admin_or_original?

    if @comment.update_attributes(params[:comment])
      redirect_to @comment.post, :notice => 'Comment successfully updated.'
    else
      redirect_to @comment.post, :alert => 'Comment could not be updated.'
    end
  end

  def destroy
    # we get @comment in admin_or_original?

    respond_to do |format|
      if @comment.destroy
        format.js
      else
        format.js { render 'error' }
      end
    end
  end

  def admin_or_original?
    @comment = Comment.find(params[:id])
    return if current_user.has_role? :admin

    if current_user != @comment.user
      redirect_to @comment.post, :alert => 'You do not have access to this page.'
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<span class="comment_info">
  <span class="blue"><%= comment.user.username %></span>
  said on <%= comment.timestamp %> (<%= distance_of_time_in_words_to_now(comment.created_at) %> ago)
</span>
<% if current_user && (current_user.has_role?(:admin) || current_user == comment.user) %>
  <span class="right controls">
    <%= link_to 'Edit', edit_comment_path(comment), :class => 'control' %>
    &nbsp;
    <%= link_to 'Delete', comment, :method => :delete, :remote => true, :confirm => 'Are you sure?', :class => 'control' %>
  </span>
<% end %>

<div class="comment_body">
  <%= markdown comment.body %>
</div>

app/views/comments/_form.html.erb
<% if current_user %>
  <div class="date">
    <%= image_tag avatar_url(current_user) %>
  </div>
  <div class="else">
    <div id="comment_form">
      <span>Write something...</span>
      <%= form_tag comments_path do %>
        <div class="field">
          <%= text_area_tag 'comment[body]' %>
        </div>
        <div class="actions">
          <%= submit_tag 'Post', :class => 'comment_submit' %>
        </div>
        <%= hidden_field_tag 'comment[post_id]', @post.id %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="date">&nbsp;</div>
  <div id="comment_form" class="else center">
    <%= link_to 'Sign up', signup_path %> or <%= link_to 'log in', login_path %> to drop a comment.
  </div>
<% end %>

app/views/comments/destroy.js.erb
$('#<%= dom_id @comment %>').fadeOut(300, function() {
  $(this).remove();
  var $el = $('#comments_count');
  var count = parseInt($el.text().split()[0]);
  if (count == 2) {
    $el.text('1 comment');
  } else {
    $el.text(parseInt(count) - 1 + ' comments');
  }
});

app/views/comments/edit.html.erb
<div id="comment_form">
  <span>Write something...</span>
  <%= form_for @comment do |f| %>
    <div class="field">
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>