config/routes.rb
Ilictronix::Application.routes.draw do

  get 'signup' => 'users#new', :as => 'signup'
  get 'login'  => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'new' => 'posts#new', :as => 'new_post'

  post '/posts/:id/publicize' => 'posts#publicize', :as => 'publicize_post'

  resources :users
  resources :sessions
  resources :posts, :except => [:show, :update, :destroy]
  resources :comments
  resources :roles

  get '/tagged/:tag' => 'posts#tagged', :as => 'tag'
  get '/tagged/:tag/:page' => 'posts#tagged'

  get '/:id' => 'posts#show', :as => 'post'
  put '/:id' => 'posts#update'
  delete '/:id' => 'posts#destroy'

  post '/users/:id/attach' => 'users#attach', :as => 'attach'

  root :to => 'posts#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_and_belongs_to_many :roles
  has_many :posts
  has_many :comments

  attr_accessible :username, :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :username
  validates_presence_of :email
  validates_uniqueness_of :username
  validates_uniqueness_of :email

  def has_role?(r)
    self.roles.where(:title => r.to_s).any?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :god_only, :only => :attach
  before_filter :admin_only, :only => :index
  before_filter :logged_in_already?, :only => :new

  def index
    @users = User.all
    render :index, :layout => 'no_sidebar'
  end

  def attach
    @user = User.find(params[:id])
    if params[:roles]

      # we cannot remove `god` from any user
      if @user.has_role? :god
        should_have_god = true
      end

      @user.roles = params[:roles].collect { |r| Role.find(r.to_i) }

      if should_have_god && !@user.has_role?(:god)
        @user.roles << Role.where(:title => 'god')
      end
    else
      @user.roles = []
    end

    respond_to do |format|
      if @user.save
        format.js
      else
        format.js { render 'error' }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @roles = Role.all.collect{ |r| [r.title, r.id] }
  end

  def new
    @user = User.new
    render :new, :layout => 'no_sidebar'
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => 'Signed up! Please login to continue.'
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => 'Logged out.'
  end

  def logged_in_already?
    return if current_user && current_user.has_role?(:god)
    if current_user
      redirect_to root_url, :alert => 'You are already logged in'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/attach.js.erb
$('#roles').empty();
$('input[type="checkbox"]:checked').each(function(i, v) {
  $('#roles').append('<li>' + $(v).next().text().toLowerCase() + '</li>');
});

app/views/users/index.html.erb
<h1>Showing All Users</h1>

<ul id="users">
  <% @users.each do |user| %>
    <li class="user" id="<%= dom_id user %>">
      <%= link_to user.username, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, 'Confirm' %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit 'Signup' %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Details for <%= @user.username %></h1>

<%= image_tag avatar_url(@user) %>

<p>Email: <%= @user.email %></p>
<p>Member since: <%= @user.created_at %></p>

<% if current_user && current_user.has_role?(:god) %>
  <hr/>
  <h3>Roles</h3>
  <ul id="roles">
    <% @user.roles.each do |role| %>
      <li><%= role.title %></li>
    <% end %>
  </ul>

  <%= form_tag attach_path(@user), :remote => true do %>
    <% @roles.each do |role| %>
      <div class="field">
        <%= check_box_tag 'roles[]', role[1], @user.has_role?(role[0]) %>
        <%= label_tag role[0] %>
      </div>
    <% end %>
    <div class="actions">
      <%= submit_tag %>
    </div>
  <% end %>
<% end %>