config/routes.rb
Ilictronix::Application.routes.draw do

  get 'signup' => 'users#new', :as => 'signup'
  get 'login'  => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'new' => 'posts#new', :as => 'new_post'

  post '/posts/:id/publicize' => 'posts#publicize', :as => 'publicize_post'

  resources :users
  resources :sessions
  resources :posts, :except => [:show, :update, :destroy]
  resources :comments
  resources :roles

  get '/tagged/:tag' => 'posts#tagged', :as => 'tag'
  get '/tagged/:tag/:page' => 'posts#tagged'

  get '/:id' => 'posts#show', :as => 'post'
  put '/:id' => 'posts#update'
  delete '/:id' => 'posts#destroy'

  post '/users/:id/attach' => 'users#attach', :as => 'attach'

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

  include ApplicationHelper # shame

  before_create :create_slug
  before_save :create_tags

  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :tags

  attr_accessible :content, :title, :post_type, :public, :tag_list
  # why do I need this?!
  attr_accessor :tag_list

  validates_presence_of :content, :title #, :post_type
  validates_length_of :content, :minimum => 10, :maximum => 2000
  validates_length_of :title, :maximum => 100

  default_scope order('created_at DESC')

  def month
    self.created_at.strftime('%b').upcase
  end

  def day
    self.created_at.strftime('%d')
  end

  def to_param
    self.slug
  end

  def as_json(options = {})
    {
      title: self.title,
      slug: self.slug,
      dom_id: "post_#{self.id}",
      date: { month: self.month,
              day: self.day },
      content: markdown(self.content),
      comments_count: self.comments.count,
      tags: self.tags.collect(&:title)
    }
  end

  private
  def create_slug
    self.slug = self.title.parameterize
  end

  def create_tags
    return if self.tag_list.nil?
    self.tags = []
    self.tag_list.split.each do |t|
      self.tags << Tag.find_or_create_by_title(t)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :require_login, :except => [:index, :tagged, :show]
  before_filter :writers_only, :only => [:new, :create]
  before_filter :admin_or_original?, :only => [:edit, :update, :publicize]
  before_filter :admin_or_original_if_private, :only => [:show]

  before_filter :attach_tag_list, :only => [:edit]

  def index
    # primitive pagination
    @page = (params[:page] || 1).to_i
    offset = 3 * (@page - 1)

    @posts = Post.where(:public => true).all(:offset => offset, :limit => 3)

    respond_to do |format|
      format.html
      format.json { render :json => @posts.to_json }
    end
  end

  def tagged
    # uses primitive pagination
    @page = (params[:page] || 1).to_i
    offset = 3 * (@page - 1)

    @tag = Tag.find_by_title(params[:tag])
    if @tag.nil?
      @posts = []
    else
      @posts = @tag.posts.where(:public => true).all(:offset => offset, :limit => 3)
    end

    respond_to do |format|
      format.html { render 'index' }
      format.json { render :json => @posts.to_json }
    end
  end

  def show
    # we get @post in admin_or_original_if_private
    @title = @post.title
  end

  def new
    @post = Post.new

    render :new, :layout => 'no_sidebar'
  end

  def create
    @post = Post.new(params[:post])
    @post.user = current_user

    if @post.save
      redirect_to @post, :notice => 'Post published successfully!'
    else
      render :new, :layout => 'no_sidebar'
    end
  end

  def edit
    # we get @post in admin_or_original?
    render :edit, :layout => 'no_sidebar'
  end

  def update
    # we get @post in admin_or_original?
    if @post.update_attributes(params[:post])
      redirect_to @post, :notice => 'Post updated successfully'
    else
      render :edit, :layout => 'no_sidebar'
    end
  end

  def destroy
    @post = Post.find_by_slug!(params[:id])
    @post.destroy
    redirect_to posts_path, :notice => 'Post deleted successfully'
  end

  # POST /posts/:id/publicize
  # makes a post public, returns JS
  def publicize
    @post = Post.find_by_slug!(params[:id])
    @post.public = true

    respond_to do |format|
      if @post.save
        format.js
      else
        format.js { render 'error' }
      end
    end
  end

  private
  def admin_or_original?
    @post = Post.find_by_slug!(params[:id])
    return if current_user.has_role? :admin

    if current_user != @post.user
      redirect_to @post, :alert => 'You do not have access to this page'
    end
  end

  def admin_or_original_if_private
    @post = Post.find_by_slug!(params[:id])
    return if current_user && current_user.has_role?(:admin)

    if !@post.public && !(current_user && current_user == @post.user)
      redirect_to root_url, :alert => 'You do not have access to this page'
    end
  end

  def attach_tag_list
    @post.tag_list = @post.tags.map{ |t| t.title }.join(' ')
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :post_type %>
    <%= f.text_field :post_type %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <%= f.hidden_field :public, :value => false %>

  <div class="field">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list %>
  </div>

  <div class="actions">
    <%= f.submit 'Preview', :id => 'post_preview' %>
    <%= f.submit 'Post', :id => 'post_submit' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<section id="<%= dom_id post %>" class="post">
  <div class="date">
    <div class="month">
      <%= post.month %>
    </div>
    <div class="day">
      <%= post.day %>
    </div>

    <% if current_user && (current_user.has_role?(:admin) || current_user == post.user) %>
      <div id="controls">
        <%= link_to 'Edit', edit_post_path(post) %><br />
        <%= link_to 'Delete', post, :method => :delete, :confirm => 'Are you sure?' %>
      </div>
    <% end %>
  </div>

  <div class="else">
    <header>
      <span class="title"><%= link_to post.title, post %></span>
      <a href="<%= post_path(post) %>#comments">
        <span class="right">
          <i class="icon-comment"></i>
          <span class="comments-count"><%= post.comments.count %></span>
        </span>
      </a>
    </header>
    <div class="fade-arrow"></div>
    <article>
      <%= markdown post.content %>

      <% if post.tags.any? %>
        <div class="tags">
          Tagged: 
          <% post.tags.each do |t| %>
            <%= link_to "\##{t.title}", tag_path(t.title) %>
          <% end %>
        </div>
      <% end %>
    </article>
    <div class="clear"></div>

    <% if !post.public %>
      <div class="important">
        <p>
          <b>NOTE:</b> This post is private, click
          <%= link_to 'here', publicize_post_path(post), :remote => true, :method => 'post' %>
          to make it public.
        </p>
      </div>
    <% end %>
  </div>

  <div class="clear"></div>
</section>

app/views/posts/_skeleton.html.erb
<div id="skeleton" class="hidden">
  <section class="post">
    <div class="date">
      <div class="month">

      </div>
      <div class="day">

      </div>
    </div>

    <div class="else">
      <header>
        <span class="title"><a href="#"></a></span>
        <a href="#">
          <span class="right">
            <i class="icon-comment"></i>
            <span class="comments-count"></span>
          </span>
        </a>
      </header>

      <div class="fade-arrow"></div>

      <article>

      </article>

      <div class="clear"></div>

    </div>

    <div class="clear"></div>
  </section>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<span id="pageno" class="hidden"><%= @page %></span>

<% if @posts.count > 0 %>
  <% @posts.each do |post| %>
    <%= render post %>
  <% end %>

  <%= render :partial => 'skeleton' %>
  
<% else %>
  <h1>Oops!</h1>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render :partial => 'form' %>

app/views/posts/publicize.js.erb
$('section#<%= dom_id @post %> .important').fadeOut(300);

app/views/posts/show.html.erb
<%= render @post %>

<section>
  <div id="comments" class="comments">
    <h2><span id="comments_count"><%= pluralize @post.comments.count, 'comment' %></span></h2>
    <% @post.comments.each do |comment| %>
      <%= div_for comment do %>
        <div class="date">
          <%= image_tag avatar_url(comment.user) %>
        </div>
        <div class="else">
          <%= render comment %>
        </div>
        <div class="clear"></div>
      <% end %>
    <% end %>

    <%= render :partial => 'comments/form' %>
  </div>
</section>