config/routes.rb
Ilictronix::Application.routes.draw do

  get 'signup' => 'users#new', :as => 'signup'
  get 'login'  => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'new' => 'posts#new', :as => 'new_post'

  post '/posts/:id/publicize' => 'posts#publicize', :as => 'publicize_post'

  resources :users
  resources :sessions
  resources :posts, :except => [:show, :update, :destroy]
  resources :comments
  resources :roles

  get '/tagged/:tag' => 'posts#tagged', :as => 'tag'
  get '/tagged/:tag/:page' => 'posts#tagged'

  get '/:id' => 'posts#show', :as => 'post'
  put '/:id' => 'posts#update'
  delete '/:id' => 'posts#destroy'

  post '/users/:id/attach' => 'users#attach', :as => 'attach'

  root :to => 'posts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ilictronix</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag "bootstrap.min", :media => "all" %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,700", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>">

  <div id="top_wrapper">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <div id="top">

      <div class="user_nav right">
        <% if current_user %>
          Logged in as <%= current_user.username %>.
          <%= link_to "Log out", logout_path %>
        <% else %>
          <%= link_to "Sign up", signup_path %> or
          <%= link_to "Log in", login_path  %>.
        <% end %>
      </div>

      <div id="brand">
        <h1><%= link_to @title || 'ilictronix.', root_url %></h1>
      </div>
    </div>
  </div>

  <div id="wrapper">
    <div id="content">
      <div class="leftcol">
        <%= yield %>
      </div>
      <div class="rightcol">
        <% if current_user && (current_user.has_role? :writer) %>
          <section>
            <header>Internal</header>
            <article>
              <ul>
                <li><%= link_to 'New Post', new_post_path %></li>
                <% if current_user.has_role? :admin %>
                  <li><%= link_to 'User Index', users_path %></li>
                <% end %>
                <% if current_user.has_role? :god %>
                  <li><%= link_to 'Roles', roles_path %></li>
                <% end %>
              </ul>
            </article>
            <div class="clear"></div>
          </section>
        <% end %>
        <%= render 'global/sidebar' %>
      </div>

      <div class="clear"></div>
    </div>

  </div>
  <%= javascript_include_tag "application" %>
  <!-- html5 shim -->
  <!--[if lt IE 9]>
  <script src="html5shiv.js"></script>
  <![endif]-->
</body>
</html>

app/views/layouts/no_sidebar.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ilictronix</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag "bootstrap.min", :media => "all" %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,700", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>">

  <div id="top_wrapper">
    <div id="top">
      <div class="user_nav right">
        <% if current_user %>
          Logged in as <%= current_user.username %>.
          <%= link_to "Log out", logout_path %>
        <% else %>
          <%= link_to "Sign up", signup_path %> or
          <%= link_to "Log in", login_path  %>.
        <% end %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>

      <div id="brand">
        <h1><%= link_to @title || 'ilictronix.', root_path %></h1>
      </div>
    </div>
  </div>

  <div id="wrapper">
    <div id="content">
      <div class="leftcol alone">
        <%= yield %>
      </div>
      <div class="clear"></div>
    </div>

    <%= render 'global/footer' %>
  </div>
  <%= javascript_include_tag "application" %>
  <!-- html5 shim -->
  <!--[if lt IE 9]>
  <script src="html5shiv.js"></script>
  <![endif]-->
</body>
</html>